/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MyStudySetsRouteImport } from './routes/my-study-sets'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudySetsIndexRouteImport } from './routes/study-sets/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as StudySetsStudySetIdRouteImport } from './routes/study-sets/$studySetId'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminFlashcardsRouteImport } from './routes/admin/flashcards'
import { Route as AdminStudySetsIndexRouteImport } from './routes/admin/study-sets/index'
import { Route as AdminStudySetsStudySetIdRouteImport } from './routes/admin/study-sets/$studySetId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MyStudySetsRoute = MyStudySetsRouteImport.update({
  id: '/my-study-sets',
  path: '/my-study-sets',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudySetsIndexRoute = StudySetsIndexRouteImport.update({
  id: '/study-sets/',
  path: '/study-sets/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudySetsStudySetIdRoute = StudySetsStudySetIdRouteImport.update({
  id: '/study-sets/$studySetId',
  path: '/study-sets/$studySetId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFlashcardsRoute = AdminFlashcardsRouteImport.update({
  id: '/admin/flashcards',
  path: '/admin/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudySetsIndexRoute = AdminStudySetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminStudySetsRoute,
} as any)
const AdminStudySetsStudySetIdRoute =
  AdminStudySetsStudySetIdRouteImport.update({
    id: '/$studySetId',
    path: '/$studySetId',
    getParentRoute: () => AdminStudySetsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/debug': typeof DebugRoute
  '/login': typeof LoginRoute
  '/my-study-sets': typeof MyStudySetsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/flashcards': typeof AdminFlashcardsRoute
  '/admin/users': typeof AdminUsersRoute
  '/study-sets/$studySetId': typeof StudySetsStudySetIdRoute
  '/admin': typeof AdminIndexRoute
  '/study-sets': typeof StudySetsIndexRoute
  '/admin/study-sets/$studySetId': typeof AdminStudySetsStudySetIdRoute
  '/admin/study-sets/': typeof AdminStudySetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/debug': typeof DebugRoute
  '/login': typeof LoginRoute
  '/my-study-sets': typeof MyStudySetsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/flashcards': typeof AdminFlashcardsRoute
  '/admin/users': typeof AdminUsersRoute
  '/study-sets/$studySetId': typeof StudySetsStudySetIdRoute
  '/admin': typeof AdminIndexRoute
  '/study-sets': typeof StudySetsIndexRoute
  '/admin/study-sets/$studySetId': typeof AdminStudySetsStudySetIdRoute
  '/admin/study-sets': typeof AdminStudySetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/debug': typeof DebugRoute
  '/login': typeof LoginRoute
  '/my-study-sets': typeof MyStudySetsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/flashcards': typeof AdminFlashcardsRoute
  '/admin/users': typeof AdminUsersRoute
  '/study-sets/$studySetId': typeof StudySetsStudySetIdRoute
  '/admin/': typeof AdminIndexRoute
  '/study-sets/': typeof StudySetsIndexRoute
  '/admin/study-sets/$studySetId': typeof AdminStudySetsStudySetIdRoute
  '/admin/study-sets/': typeof AdminStudySetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/debug'
    | '/login'
    | '/my-study-sets'
    | '/profile'
    | '/register'
    | '/admin/flashcards'
    | '/admin/users'
    | '/study-sets/$studySetId'
    | '/admin'
    | '/study-sets'
    | '/admin/study-sets/$studySetId'
    | '/admin/study-sets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/debug'
    | '/login'
    | '/my-study-sets'
    | '/profile'
    | '/register'
    | '/admin/flashcards'
    | '/admin/users'
    | '/study-sets/$studySetId'
    | '/admin'
    | '/study-sets'
    | '/admin/study-sets/$studySetId'
    | '/admin/study-sets'
  id:
    | '__root__'
    | '/'
    | '/debug'
    | '/login'
    | '/my-study-sets'
    | '/profile'
    | '/register'
    | '/admin/flashcards'
    | '/admin/users'
    | '/study-sets/$studySetId'
    | '/admin/'
    | '/study-sets/'
    | '/admin/study-sets/$studySetId'
    | '/admin/study-sets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DebugRoute: typeof DebugRoute
  LoginRoute: typeof LoginRoute
  MyStudySetsRoute: typeof MyStudySetsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  AdminFlashcardsRoute: typeof AdminFlashcardsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  StudySetsStudySetIdRoute: typeof StudySetsStudySetIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  StudySetsIndexRoute: typeof StudySetsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-study-sets': {
      id: '/my-study-sets'
      path: '/my-study-sets'
      fullPath: '/my-study-sets'
      preLoaderRoute: typeof MyStudySetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-sets/': {
      id: '/study-sets/'
      path: '/study-sets'
      fullPath: '/study-sets'
      preLoaderRoute: typeof StudySetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-sets/$studySetId': {
      id: '/study-sets/$studySetId'
      path: '/study-sets/$studySetId'
      fullPath: '/study-sets/$studySetId'
      preLoaderRoute: typeof StudySetsStudySetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/flashcards': {
      id: '/admin/flashcards'
      path: '/admin/flashcards'
      fullPath: '/admin/flashcards'
      preLoaderRoute: typeof AdminFlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/study-sets/': {
      id: '/admin/study-sets/'
      path: '/'
      fullPath: '/admin/study-sets/'
      preLoaderRoute: typeof AdminStudySetsIndexRouteImport
      parentRoute: typeof AdminStudySetsRoute
    }
    '/admin/study-sets/$studySetId': {
      id: '/admin/study-sets/$studySetId'
      path: '/$studySetId'
      fullPath: '/admin/study-sets/$studySetId'
      preLoaderRoute: typeof AdminStudySetsStudySetIdRouteImport
      parentRoute: typeof AdminStudySetsRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DebugRoute: DebugRoute,
  LoginRoute: LoginRoute,
  MyStudySetsRoute: MyStudySetsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  AdminFlashcardsRoute: AdminFlashcardsRoute,
  AdminUsersRoute: AdminUsersRoute,
  StudySetsStudySetIdRoute: StudySetsStudySetIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  StudySetsIndexRoute: StudySetsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
